### PR TITLE
Multiple Fixes for New Prod Relis

### PR DESCRIPTION
**Pull request by gauranshkumar**
1. File System Access Permission fix
2. Fix Nginx Conf for tomcat
3. Email sending Fix

### CODE REVIEW

**Comment by gauranshkumar** [comment]
**PR Work In Progress**, Needs more fix and testing

**Comment by gauranshkumar** [comment]
Fixed major Deployment Blocker of tomcat routing via Nginx in 2f2682d.

**Comment by gauranshkumar** [comment]
Also added Bibler as a local docker service for prod deployment.

**Comment by gauranshkumar** [comment]
@esyriani Please review this whenever possible for you to merge prod with the latest changes.

**Comment by esyriani** [comment]
@sarthakray2 could you test this?

**Pull request merged**
